const projects=[
 {code:'EB-2601',name:'Al Narjis Residential Villas',client:'Riyadh Living Co.',value:'SAR 12.8M',progress:72,status:'On Track'},
 {code:'EB-2602',name:'Olaya Commercial Fit-out',client:'Afaq Properties',value:'SAR 6.4M',progress:48,status:'Attention'},
 {code:'EB-2603',name:'Riyadh Logistics Hub',client:'Najd Logistics',value:'SAR 18.2M',progress:31,status:'On Track'},
 {code:'EB-2604',name:'King Fahd Office Renovation',client:'Meridian Group',value:'SAR 4.7M',progress:86,status:'On Track'},
 {code:'EB-2605',name:'Diriyah Staff Accommodation',client:'Wadi Developments',value:'SAR 6.5M',progress:18,status:'Delayed'}
];
const moduleInfo={
 projects:[['Live Projects','12','▱'],['Tender Pipeline','SAR 31.2M','◈'],['Budget Variance','-2.8%','⌁'],['Milestones Due','8','◷'],['Change Orders','SAR 1.4M','↻'],['Project Risks','6 open','△']],
 procurement:[['Purchase Requests','14 open','◇'],['Purchase Orders','SAR 2.8M','▧'],['Pending GRNs','7','▣'],['Supplier Invoices','23','▤'],['Vendor Performance','92%','☆'],['Framework Contracts','8 active','⌘']],
 inventory:[['Stock Value','SAR 3.84M','▦'],['Warehouses','4','⌂'],['Low-stock Items','16','!'],['Reusable Assets','386','↻'],['Material Issues','42 today','⇥'],['Cycle Counts','96%','✓']],
 workforce:[['Employees','184','♙'],['Site Workers','137','♟'],['Attendance','94.6%','✓'],['Payroll Estimate','SAR 1.92M','◫'],['Overtime','486 hrs','◷'],['Open Positions','9','+']],
 finance:[['Revenue YTD','SAR 28.4M','↗'],['Project Costs','SAR 20.1M','↘'],['Gross Margin','29.2%','◉'],['Receivables','SAR 6.7M','◫'],['Cash Forecast','SAR 4.2M','⌁'],['Unposted Entries','11','▤']],
 approvals:[['My Approvals','7','✓'],['Purchase Orders','3','◇'],['Payment Requests','2','◫'],['Leave Requests','1','♙'],['Change Orders','1','↻'],['Completed Today','12','✓']],
 reports:[['Executive Pack','Monthly','▤'],['Project Profitability','Live','⌁'],['Budget vs Actual','Live','◫'],['Cash Flow Forecast','13 weeks','↗'],['Procurement Analytics','Monthly','◇'],['Workforce Analytics','Live','♙']]
};
const titles={dashboard:['Executive workspace','Good afternoon, Hafiz'],projects:['Operations / Projects','Project portfolio'],procurement:['Operations / Procurement','Procurement control'],inventory:['Operations / Inventory','Inventory & reusable assets'],workforce:['Operations / Workforce','Workforce management'],finance:['Control / Finance','Financial control'],approvals:['Control / Approvals','Approval centre'],reports:['Control / Reports','Management reports']};
const content=document.getElementById('content');
function kpi(label,value,icon,delta='8.4%',down=false){return `<article class="card kpi-card"><div class="kpi-head"><span>${label}</span><span class="kpi-icon">${icon}</span></div><h3>${value}</h3><div class="trend ${down?'down':''}"><b>${down?'↓':'↑'} ${delta}</b> vs previous period</div></article>`}
function dashboard(){
 const bars=[62,74,55,81,70,88,78,92];
 return `<div class="hero-row"><div><h1>Portfolio performance</h1><p>Live operational position across Elevate Builders • 13 July 2026</p></div><div class="period"><button>Month</button><button class="active">Quarter</button><button>Year</button></div></div>
 <div class="kpi-grid">${kpi('Contract Value','SAR 48.6M','↗','12.6%')}${kpi('Certified Revenue','SAR 28.4M','◫','9.2%')}${kpi('Gross Margin','29.2%','◉','2.1%')}${kpi('Cash Collected','SAR 21.7M','✓','4.3%',true)}</div>
 <div class="dash-grid"><article class="card"><div class="card-title"><h3>Budget vs actual cost</h3><button data-action>View analysis →</button></div><div class="chart">${bars.map((h,i)=>`<div class="bar-group"><i class="bar" style="height:${Math.min(96,h+8)}%"></i><i class="bar actual" style="height:${h}%"></i><span>${['Dec','Jan','Feb','Mar','Apr','May','Jun','Jul'][i]}</span></div>`).join('')}</div><div class="legend"><span><i></i>Actual cost</span><span><i></i>Approved budget</span></div></article>
 <article class="card"><div class="card-title"><h3>Project health</h3><button data-action>Details →</button></div><div class="donut-wrap"><div class="donut"></div><div class="status-list"><div><i style="background:#1e9b72"></i>On track <b>7</b></div><div><i style="background:#7367c7"></i>Planning <b>3</b></div><div><i style="background:#d58a1b"></i>Attention <b>1</b></div><div><i style="background:#d75a63"></i>Delayed <b>1</b></div></div></div></article></div>
 <div class="lower-grid"><article class="card"><div class="card-title"><h3>Priority projects</h3><button data-page-link="projects">View all projects →</button></div>${projectTable(projects.slice(0,4))}</article>
 <article class="card"><div class="card-title"><h3>Recent activity</h3><button data-action>View audit trail →</button></div>${[['✓','PO-260718 approved','Commercial Director approved SAR 186,400','8 min ago'],['⇥','Materials issued','Al Narjis Villas • 36 line items','34 min ago'],['◫','Payment certificate posted','Riyadh Logistics Hub • IPC-04','1 hr ago'],['♙','Attendance synchronized','All four project sites','2 hrs ago']].map(a=>`<div class="activity"><span>${a[0]}</span><div><b>${a[1]}</b><p>${a[2]}</p><small>${a[3]}</small></div></div>`).join('')}</article></div>`
}
function projectTable(rows){return `<div class="table-wrap"><table><thead><tr><th>PROJECT</th><th>CONTRACT VALUE</th><th>PROGRESS</th><th>STATUS</th></tr></thead><tbody>${rows.map(p=>`<tr data-action><td><div class="project-cell"><span>${p.name.charAt(0)}</span><div><b>${p.name}</b><small>${p.code} • ${p.client}</small></div></div></td><td>${p.value}</td><td><div style="display:flex;align-items:center;gap:8px"><div class="progress"><i style="width:${p.progress}%"></i></div>${p.progress}%</div></td><td><span class="badge ${p.status==='Attention'?'amber':p.status==='Delayed'?'red':''}">${p.status}</span></td></tr>`).join('')}</tbody></table></div>`}
function modulePage(page){const items=moduleInfo[page];return `<div class="hero-row"><div><h1>${titles[page][1]}</h1><p>Connected information and controls for faster, accountable decisions.</p></div><div class="page-tools"><button data-action>Export</button><button class="action-btn primary-small" data-action>+ New transaction</button></div></div><div class="filters"><input placeholder="Search records, documents or reference…"><select><option>All statuses</option><option>Open</option><option>Approved</option></select></div><div class="module-grid">${items.map((x,i)=>`<article class="card module-card" data-action><div class="module-top"><span class="kpi-icon">${x[2]}</span><span class="badge ${i===2?'amber':''}">${i%2?'Updated today':'Live'}</span></div><h3>${x[0]}</h3><p>Monitor, review and manage ${x[0].toLowerCase()} from one controlled workspace.</p><footer><b>${x[1]}</b><span>Open →</span></footer></article>`).join('')}</div>${page==='projects'?`<article class="card" style="margin-top:17px"><div class="card-title"><h3>All active projects</h3><button data-action>Portfolio report →</button></div>${projectTable(projects)}</article>`:''}`}
function render(page){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===page));document.getElementById('crumb').textContent=titles[page][0];document.getElementById('pageTitle').textContent=titles[page][1];content.innerHTML=page==='dashboard'?dashboard():modulePage(page);document.querySelector('.sidebar').classList.remove('open');window.scrollTo(0,0)}
function toast(message='Demo interaction completed'){const t=document.getElementById('toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1900)}
document.getElementById('signIn').onclick=()=>{document.getElementById('login').classList.add('hidden');document.getElementById('app').classList.remove('hidden');render('dashboard')};
document.getElementById('logout').onclick=()=>{document.getElementById('app').classList.add('hidden');document.getElementById('login').classList.remove('hidden')};
document.getElementById('menuToggle').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');
document.addEventListener('click',e=>{const n=e.target.closest('[data-page]');if(n)render(n.dataset.page);const l=e.target.closest('[data-page-link]');if(l)render(l.dataset.pageLink);const period=e.target.closest('.period button');if(period){document.querySelectorAll('.period button').forEach(x=>x.classList.remove('active'));period.classList.add('active');toast(`Period changed to ${period.textContent}`)}if(e.target.closest('[data-action]'))toast()});
